### ISSUE TITLE
index.js, function bfy: very broken design

### ISSUE THREAD

**Issue by mk-pmb** [shama/scriptify#5]
In the current PR, I was going to ask which problem is being solved by re-arranging the order of arguments, so I could suggest how to better convey the intent in the code.
However, reading the old code, I discovered the entire approach with `writeFileSync` in a webserver request handler, and then calling browserify's CLI on a temporary file, is so fubar that clarity of the PR's code probably won't matter.
Ideas for better approaches, in case someone wants to fix it:
* There are some common pitfalls with temporary files, about their names and permissions. Both seem to apply here.
  * One of the problems: Current filenames aren't guaranteed to be unique even with just one single instance of the module running at the same time.
* Browserify has an API that could probably take your stream, buffer or string directly, in memory, without having to wait for a file system to first write and then read all of it. Don't get me started on file system timing bugs.
  * One of the problems: You could get incomplete or stale data even if your filenames were unique to begin with. At least do a fsync - you cannot trust it but you can at least claim to have tried, at all, to care about data integrity.
* If you really like the CLI for whatever reason, and the fact it has to initialize a new nodejs process and browserify instance each time, try to pass your data via one of the child_process's file descriptors, instead of a disk file.
* Implement caching so you have to browserify the same data only once.

That said, I like the module idea itself, and people should understand from the README that this isn't meant for production, so it's probably acceptable to have it work "most of the time". My main concern is to ensure awareness, so people won't copy the approach for any important modules.

**Comment by shama** [comment]
Oh ok, thanks for your thoughts.
